### ISSUE TITLE
Email sent as noreply@example.com

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#158]
Production email is sent as ``DEAR Petition <noreply@example.com>``. We should probably change this to ``noreply@dear-petition.herokuapp.com``

**Comment by robert-w-gries** [comment]
In the past, I've also had to update the `site` value in our DB from `example.com`.  Otherwise, it results in emails having the `FROM` field set to `admin@example.com`.

It looks like [a migration sets example as the default domain](https://github.com/deardurham/dear-petition/blob/76cf5b475961433544b3220a330bf167892d7ef4/dear_petition/contrib/sites/migrations/0003_set_site_domain_and_name.py#L14). I'm not sure if there's a better default value or if we should include documentation to let the user know they should update it.

**Comment by georgehelman** [comment]
https://github.com/deardurham/dear-petition/pull/176
