### ISSUE TITLE
Improve Local Setup Documentation

### ISSUE THREAD

**Issue by dchukhin** [deardurham/dear-petition#88]
I tried to go through the non-Docker local setup docs today, and was surprised that they stop after installing requirments, without instructions about setting up a database, running the server, etc. locally. If the project supports non-Docker setups, then we should either
 - a) give instructions on how to set up the rest of the project locally without Docker, or
 - b) remove the non-Docker section

**Comment by copelco** [comment]
@robert-w-gries: since this is a few months old, based on your local setup experience, do you have any opinions on this?

**Comment by robert-w-gries** [comment]
I haven't done a local backend + DB setup before, just a local frontend setup.

That being said, I agree that there is some missing info regarding how the database and django should be connected. If we keep the local backend instructions, there should be a pointer to the `.envs/.local` files so the user can configure the DB + backend properly.

However, I think it's fair to remove the local setup instructions because I don't think any of the current developers are using a local setup. We should emphasize the docker instructions, and in the rare case where someone can't use docker we can provide more specific instruction through Github or Slack. Additionally, the docker config files self-document our setup process so we can always point devs to those first.
